name: Cleanup Test Resources

on:
  workflow_dispatch:
    inputs:
      mode:
        description: 'Cleanup mode'
        required: true
        default: 'dry-run'
        type: choice
        options:
          - dry-run
          - interactive
      region:
        description: 'AWS region'
        required: false
        default: 'us-east-1'

permissions:
  contents: read

jobs:
  cleanup:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    env:
      AWS_REGION: ${{ github.event.inputs.region || 'us-east-1' }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      
      # Configure AWS credentials using access keys per company policy
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.DATA_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DATA_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Install dependencies
        run: |
          pip install boto3
      
      - name: List resources (dry-run mode)
        if: ${{ github.event.inputs.mode == 'dry-run' }}
        run: |
          echo "Running in DRY-RUN mode - no resources will be deleted"
          python scripts/cleanup_test_resources.py --region ${{ env.AWS_REGION }} --dry-run
      
      - name: Run interactive cleanup
        if: ${{ github.event.inputs.mode == 'interactive' }}
        run: |
          echo "Running in INTERACTIVE mode"
          echo "This workflow will list resources and allow selection for deletion"
          echo ""
          echo "To delete resources, you'll need to:"
          echo "1. Review the list of playgrounds and IAM users"
          echo "2. Run the script locally with proper AWS credentials"
          echo "3. Or modify this workflow to accept resource IDs as inputs"
          echo ""
          echo "Currently listing resources in dry-run mode:"
          python scripts/cleanup_test_resources.py --region ${{ env.AWS_REGION }} --dry-run
          echo ""
          echo "To actually delete resources, please run the script locally:"
          echo "  python scripts/cleanup_test_resources.py --region ${{ env.AWS_REGION }}"
      
      - name: Summary
        if: always()
        run: |
          echo "Cleanup workflow completed"
          echo "Mode: ${{ github.event.inputs.mode }}"
          echo "Region: ${{ env.AWS_REGION }}"
