name: Deploy Infra (Terraform Workspaces)

on:
  push:
    branches: [ master ]
    paths:
      - 'infra/**'
      - '.github/workflows/deploy-infra.yml'
      - '.github/workflows/bootstrap-terraform.yml'
  workflow_dispatch:

jobs:
  bootstrap:
    uses: ./.github/workflows/bootstrap-terraform.yml
    secrets: inherit

  deploy:
    needs: bootstrap
    runs-on: ubuntu-latest

    strategy:
      matrix:
        env: [dev]

    permissions:
      contents: read

    env:
      AWS_REGION: ${{ vars.AWS_REGION || 'us-east-1' }}
      TF_IN_AUTOMATION: "true"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.DATA_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DATA_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: (Optional) Build Lambda Layer
        working-directory: infra/layer
        run: |
          if [ -f requirements.txt ]; then
            bash build_layer.sh || true
          fi

      - name: Terraform Init
        working-directory: infra
        run: terraform init -input=false

      - name: Select/Create Workspace
        working-directory: infra
        run: |
          set -euo pipefail

          WS="${{ matrix.env }}"
          echo "Ensuring Terraform workspace '${WS}' exists..."
          if terraform workspace list | sed 's/^[* ]*//' | grep -Fxq "$WS"; then
            echo "Selecting existing workspace: $WS"
            terraform workspace select "$WS"
          else
            echo "Creating new workspace: $WS"
            terraform workspace new "$WS"
          fi
          echo "Current workspace: $(terraform workspace show)"

          # Ensure backend directory exists if re-run
          if [ ! -d .terraform ]; then
            echo "Terraform not initialized yet; running 'terraform init'..."
            terraform init -input=false
          fi

          STATE_KEY="env:/${WS}/aimodelshare/infra/terraform.tfstate"
          echo "Checking if remote state object exists: ${STATE_KEY}"
          if aws s3api head-object --bucket "aimodelshare-tfstate-prod-copilot-2024" --key "${STATE_KEY}" >/dev/null 2>&1; then
            echo "Remote state object exists for workspace '${WS}'"
          else
            echo "Remote state object missing for workspace '${WS}' - creating initial state"
            terraform apply -auto-approve -target=null_resource.state_seed
          fi

          echo "Workspace '$WS' ready; proceeding to plan/apply steps."

      - name: Terraform Validate
        working-directory: infra
        run: terraform validate

      - name: Terraform Plan
        id: plan
        working-directory: infra
        run: terraform plan -input=false -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/master'
        working-directory: infra
        run: terraform apply -input=false -auto-approve tfplan

      - name: Show Outputs
        working-directory: infra
        run: terraform output -json

      - name: Run API Integration Tests
        if: github.ref == 'refs/heads/master'
        working-directory: .
        run: |
          # Extract API base URL from Terraform outputs
          API_BASE_URL=$(cd infra && terraform output -raw api_base_url)
          echo "API Base URL: $API_BASE_URL"
          
          # Validate that we got a proper URL
          if [[ -z "$API_BASE_URL" || "$API_BASE_URL" == "null" ]]; then
            echo "❌ Failed to get API base URL from Terraform outputs"
            exit 1
          fi
          
          # Install requests library for API testing
          python -m pip install --upgrade pip
          python -m pip install requests
          
          # Wait a moment for API to be fully available
          echo "⏳ Waiting for API to be fully available..."
          sleep 15
          
          # Run API integration tests
          echo "🚀 Starting API Integration Tests..."
          python tests/test_api_integration.py "$API_BASE_URL"

      - name: Install Load Test Dependencies
        if: github.ref == 'refs/heads/master' && (vars.RUN_LOAD_TESTS != 'false')
        working-directory: .
        run: |
          # Install additional dependencies for load tests
          python -m pip install aiohttp rich

      - name: Run Load Tests - Single Table
        if: github.ref == 'refs/heads/master' && (vars.RUN_LOAD_TESTS != 'false')
        working-directory: .
        run: |
          # Extract API base URL from Terraform outputs (reuse from integration tests)
          API_BASE_URL=$(cd infra && terraform output -raw api_base_url)
          export API_BASE_URL
          
          echo "🚀 Running Single Table Load Test..."
          python tests/load_single_table.py

      - name: Run Load Tests - Multi Table
        if: github.ref == 'refs/heads/master' && (vars.RUN_LOAD_TESTS != 'false')
        working-directory: .
        run: |
          # Extract API base URL from Terraform outputs (reuse from integration tests)
          API_BASE_URL=$(cd infra && terraform output -raw api_base_url)
          export API_BASE_URL
          
          echo "🚀 Running Multi Table Load Test..."
          python tests/load_multi_table.py

      - name: Run Load Tests - Mixed Duration
        if: github.ref == 'refs/heads/master' && (vars.RUN_LOAD_TESTS != 'false')
        working-directory: .
        env:
          LOAD_DURATION_SECONDS: 20
        run: |
          # Extract API base URL from Terraform outputs (reuse from integration tests)
          API_BASE_URL=$(cd infra && terraform output -raw api_base_url)
          export API_BASE_URL
          
          echo "🚀 Running Mixed Duration Load Test (20s for CI)..."
          python tests/load_mixed_duration.py
