name: Destroy Infra (Terraform, OIDC, Workspaces)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Workspace to destroy (dev|stage|prod)'
        required: true
        default: 'dev'
      destroy_bootstrap:
        description: 'Also destroy bootstrap resources (S3 bucket and DynamoDB table) - USE WITH EXTREME CAUTION'
        required: false
        default: false
        type: boolean

jobs:
  destroy:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    env:
      AWS_REGION: ${{ vars.AWS_REGION || 'us-east-1' }}
      TF_IN_AUTOMATION: "true"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5
          terraform_wrapper: false

      # Configure AWS credentials using access keys per company policy
      # Note: Requires AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY repository secrets
      # Security: Ensure access keys follow principle of least privilege and key rotation policies
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.DATA_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DATA_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init (Main Infrastructure)
        working-directory: infra
        run: terraform init -input=false

      - name: Select/Create Workspace and Import Shared DynamoDB Table
        working-directory: infra
        run: |
          set -euo pipefail

          WS="${{ github.event.inputs.environment }}"
          echo "Ensuring Terraform workspace '${WS}' exists..."

          # Normalize workspace names from 'terraform workspace list'
          if terraform workspace list | sed 's/^[* ]*//' | grep -Fxq "$WS"; then
            echo "Selecting existing workspace: $WS"
            terraform workspace select "$WS"
          else
            echo "Creating new workspace: $WS"
            terraform workspace new "$WS"
          fi

          echo "Current workspace: $(terraform workspace show)"

          # Verify backend is initialized (in case this step runs before init in your workflow)
          if [ ! -d .terraform ]; then
            echo "Terraform not initialized yet; running 'terraform init'..."
            terraform init -input=false
          fi

          # Import shared DynamoDB table if not already in state.
          # This prevents 'ResourceInUseException' on apply for the shared table.
          if terraform state show aws_dynamodb_table.playground >/dev/null 2>&1; then
            echo "Shared DynamoDB table 'PlaygroundScores' already tracked in state for workspace '$WS'."
          else
            echo "Importing shared DynamoDB table 'PlaygroundScores' into state for workspace '$WS'..."
            terraform import aws_dynamodb_table.playground PlaygroundScores
          fi

          echo "Workspace '$WS' ready; proceeding to plan/apply steps."


      - name: Terraform Destroy (Main Infrastructure)
        working-directory: infra
        run: terraform destroy -input=false -auto-approve

      - name: Destroy Bootstrap Resources
        if: github.event.inputs.destroy_bootstrap == 'true'
        working-directory: infra/bootstrap
        run: |
          echo "⚠️  WARNING: Destroying bootstrap resources (S3 bucket and DynamoDB table)"
          echo "This will remove the Terraform state storage and could cause data loss!"
          
          # Initialize bootstrap Terraform
          terraform init -input=false
          
          # Check if state bucket is empty (except for our state files)
          BUCKET_NAME="aimodelshare-tfstate-prod-copilot-2024"
          OBJECT_COUNT=$(aws s3api list-objects-v2 --bucket "$BUCKET_NAME" --query 'Contents | length(@)' --output text 2>/dev/null || echo "0")
          
          # AWS CLI returns 'None' for empty buckets, 'null' if bucket doesn't exist, or a number for non-empty buckets
          if [[ "$OBJECT_COUNT" =~ ^[0-9]+$ ]] && [ "$OBJECT_COUNT" -gt 0 ]; then
            echo "⚠️  S3 bucket contains $OBJECT_COUNT objects. Emptying bucket first..."
            aws s3 rm s3://$BUCKET_NAME --recursive
          else
            echo "✅ S3 bucket is empty or doesn't exist (count: $OBJECT_COUNT), proceeding with destroy..."
          fi
          
          # Destroy bootstrap resources
          terraform destroy -input=false -auto-approve
          
          echo "✅ Bootstrap resources destroyed"
