name: Unit Tests for Playground Components

on:
  workflow_dispatch: # Manual trigger
  pull_request:
    paths:
      - 'aimodelshare/**'
      - 'tests/**'
      - '.github/workflows/unit-tests.yml'
  push:
    branches:
      - master
      - main

permissions:
  contents: read

concurrency:
  group: unit-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      matrix:
        test-group:
          - setup_sanity
          - credentials
          - playground_init
          - data_preprocessing
          - model_training
          - playground_operations

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install pytest pytest-cov
          pip install pandas numpy scikit-learn seaborn
          pip install -e .

      - name: Run unit tests for ${{ matrix.test-group }}
        run: |
          pytest -vv tests/unit/test_${{ matrix.test-group }}.py --tb=short

      - name: Run unit tests with coverage
        if: matrix.test-group == 'credentials'
        run: |
          pytest tests/unit/ --cov=aimodelshare --cov-report=xml --cov-report=term

      - name: Upload coverage report
        if: matrix.test-group == 'credentials'
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml

  summary:
    needs: unit-tests
    runs-on: ubuntu-latest
    if: always()
    
    steps:
      - name: Check test results
        run: |
          echo "All unit test groups completed"
          echo "Review individual test results above"
